# Generated by Django 5.1.5 on 2025-02-07 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apiv1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('description', models.URLField()),
                ('package', models.FloatField()),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiv1.student')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobsv1.job')),
            ],
            options={
                'verbose_name': 'Application Status',
                'verbose_name_plural': 'Application Status',
            },
        ),
    ]
