# Generated by Django 5.1.5 on 2025-02-19 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsv1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='jd',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(),
        ),
    ]
