# Generated by Django 5.1.5 on 2025-02-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsv1', '0002_job_jd_alter_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationstatus',
            name='remark',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
