# Generated by Django 5.1.5 on 2025-03-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobsv1', '0003_applicationstatus_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(default='Eligible', max_length=100),
        ),
    ]
