# Generated by Django 5.1.5 on 2025-02-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0002_certificate_certificate_id_certificate_issue_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='branch',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
