# Generated by Django 5.1.5 on 2025-02-20 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0003_education_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='links',
            new_name='github_link',
        ),
        migrations.AddField(
            model_name='project',
            name='hosted_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='branch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='branch',
            field=models.CharField(blank=True, choices=[('IT', 'Information Technology'), ('CSE', 'Computer Software Engineering'), ('CSE-AIML', 'Computer Software Engineering'), ('CSE-DS', 'Computer Software Engineering'), ('CSE-BS', 'Computer Software Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EX', 'Electrical & Electronics Engineering'), ('AU', 'Automobile Engineering'), ('ME', 'Mechanical Engineering')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='job_status',
            field=models.CharField(default='Unplaced', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='permanent_address',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
