# Generated by Django 5.1.5 on 2025-02-24 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0005_accomplishments_competitiveexams'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='job_status',
        ),
    ]
