# Generated by Django 5.1.5 on 2025-03-01 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiv1', '0006_remove_student_job_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='job_status',
            field=models.CharField(default='Unplaced', max_length=50),
        ),
    ]
